# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marching Gray Young
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am web front-end developer, as well as a web designer. In here, you can find my resume, movies or TVs that I have watched, music that I like, and some JavaScript packages I build.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grayyoung.github.io" # the base hostname & protocol for your site
github_username:  grayyoung

# Build settings
markdown: kramdown

exclude:
  - _site
  - bower_components
  - node_modules
  - [LICENSE, README.md, bower.json, package.json, gulpfile.js]

sass:
  style: compressed

paginate: 20
paginate_path: "/blog/page:num/"

collections:
  Holy_Bible:
    output: true
    permalink: /bible/:path/

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap