# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marching Gray Young
email: windpet@live.cn
description: # this means to ignore newlines until "baseurl:"
  I am web front-end developer, as well as a web designer. In here, you can find my resume, movies or TVs that I have watched, music that I like, and some JavaScript packages I build.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grayyoung.github.io" # the base hostname & protocol for your site
github_username:  grayyoung

# Build settings
markdown: kramdown
encoding: "utf-8"

exclude:
  - node_modules
  - _site
  - LICENSE
  - README.md
  - package.json
  - package.map
  - gulpfile.js

sass:
  load_paths:
    - node_modules
  style: compressed

paginate: 8
paginate_path: "/blog/page:num/"

collections:
  Holy_Bible:
    permalink: "/bible/:name"
    output: true
  Addicted:
    permalink: "/addicted/:name"
    output: true
  Examination:
    permalink: "/examination/:name"
    output: true

defaults:
  - scope:
      path: ""
      type: Holy_Bible
    values:
      layout: article
      breadcrumbs: 
        - name: "Holy Bible"
          url: "000.html"
      thumbnail: "/images/thumb/tb-bible.jpg"
  - scope:
      path: ""
      type: Addicted
    values:
      layout: article
      breadcrumbs: 
        - name: "你丫上瘾了？"
          url: "000.html"
      thumbnail: "/images/thumb/tb-addicted.png"
  - scope:
      path: ""
      type: Examination
    values:
      layout: examination
      breadcrumbs: 
        - name: "Examination Papers"
          url: "/examination/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
