name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: read
  deployments: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare packages
      run: |
        rm node_modules -rf
        npm cache clean --force
        npm install
    - name: Build page with Jekyll
      uses: actions/jekyll-build-pages@v1-beta
      with:
        future: true
        verbose: true
    - name: Archive build output
      run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with: 
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn

  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1-beta


